[servidor]
endereco = "127.0.0.1"
porta = 3000

# Gerando token de acesso:
# echo -n $(echo -n 41271254000121; h=($(cat certificado-cliente-1.pfx | sha256sum )); echo -n $h; echo -n 12345678nfepb) | sha256sum

[[implantacao]]
empresa = { documento = "41271254000121" }
certificado = { caminho = "/home/fiscalidade_server/.fiscalidade_server/certificado-1.pfx", senha = "12345678" }
servico = { tipo = "nfe", estado = "pb", ambiente = "producao" }

[[implantacao]]
empresa = { documento = "02904998000184" }
certificado = { caminho = "/home/fiscalidade_server/.fiscalidade_server/certificado-2.pfx", senha = "87654321" }
servico = { tipo = "nfce", estado = "mt", ambiente = "homologacao" }
